import { ISection } from './../interface/section.interface';
export const SECTIONS: ISection[] = [
  {
    id: 'personalDetails',
    title: 'Personal Details',
    routerLink: 'personal-details',
    nextSection: 'contact-details',
    previousSection: '',
  },
  {
    id: 'contactDetails',
    title: 'Contact Details',
    routerLink: 'contact-details',
    nextSection: 'skills',
    previousSection: 'personal-details',
  },
  {
    id: 'skills',
    title: 'Skills',
    routerLink: 'skills',
    nextSection: 'experience',
    previousSection: 'contact-details',
  },
  {
    id: 'experience',
    title: 'Experience',
    routerLink: 'experience',
    nextSection: 'education',
    previousSection: 'skills',
  },
  {
    id: 'education',
    title: 'Education',
    routerLink: 'education',
    nextSection: 'personal-projects',
    previousSection: 'experience',
  },
  {
    id: 'personalProjects',
    title: 'Personal Projects',
    routerLink: 'personal-projects',
    nextSection: 'certificates',
    previousSection: 'education',
  },
  {
    id: 'certificates',
    title: 'Certificates',
    routerLink: 'certificates',
    nextSection: 'interests',
    previousSection: 'personal-projects',
  },
  {
    id: 'interests',
    title: 'Interests',
    routerLink: 'interests',
    nextSection: 'summary',
    previousSection: 'certificates',
  },
  {
    id: 'summary',
    title: 'Summary',
    routerLink: 'summary',
    nextSection: '',
    previousSection: 'interests',
  },
];
